// Generated by https://quicktype.io

export interface CategoryInterface {
  subCategory: string[];
  _id: string;
  category: string;
  userId: string;
  accountBook: string;
  createdAt: string;
  updatedAt: string;
}
