// Generated by https://quicktype.io

export interface TodoListInterface {
  _id: string;
  taskId: string;
  title: string;

  note: string;
  status: boolean;
}

export interface TaskList {
  name: string;
}

export interface TodoInterface {
  _id: string;
  taskId: string;
  title: string;
  createdAt: string;
  note: string;
  status: boolean;
}
